name: Build APK

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v4.6.0
      with:
        java-version: '17'  # Updated to Java 17
        distribution: 'temurin'  # Use 'temurin' as the JDK distribution
        java-package: 'jdk'  # Use the JDK package (you can also specify jre, jdk+fx, etc.)
        architecture: 'x64'  # Use x64 architecture
        check-latest: 'true'  # Ensure it checks for the latest available JDK version

    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew  # Grant execute permissions to the gradlew script

    - name: Install dependencies
      run: |
        ./gradlew clean build  # Adjust this command based on your project setup

    - name: Build APK
      run: |
        ./gradlew assembleRelease  # Adjust this command based on your project setup

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk  # Adjust the path based on your APK output
