name: Build with Caching

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 3: Set up Java JDK
    - name: Setup Java JDK
      uses: actions/setup-java@v4.6.0
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 4: Build APK
    - name: Build APK
      run: |
        ./gradlew clean build

    # Step 5: Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk
